---
title: "Historical state union density"
author: 'Daniel Perez, EARN/EPI'
---

```{r Libraries, message=FALSE}

library(tidyverse)
library(here)
library(epiextractr)

```

Load CPS data using [epiextractr](epi_microdata.qmd)

```{r epiextractr}

org <- load_org(1983:2022, year, month, statefips, orgwgt, union, unmem, cow1, age, emp, unemp, lfstat, pubsec, selfemp, selfinc,
                .extracts_dir = here('data/cps/')) %>%
  filter(age>=16) %>%
  #remove self-employed and self-incorporated workers from sample
  mutate(selfemp0 = ifelse(selfemp==1 & !is.na(selfemp), yes=1, no=0),
         selfinc0 = ifelse(selfinc==1 & !is.na(selfinc), yes=1, no=0)) %>%
  filter(selfemp0==0, selfinc0==0)

```

Calculate US union density 1983--2022

```{r National}

#US union members and union represented by year, 1983-2022

density_us_org <- org %>% 
  group_by(year) %>% 
  summarise(represented_share = weighted.mean(union, w=orgwgt/12, na.rm=TRUE),
            rep_n = sum(union, na.rm=TRUE),
            member_share = weighted.mean(unmem, w=orgwgt/12, na.rm=TRUE),
            memb_n = sum(unmem, na.rm=TRUE),
            wgt_memb = sum(unmem * orgwgt/12, na.rm=TRUE))

density_us_org
```

Calculate state level union representation, 1983--2022

```{r Year and state}

#Union representation by year and state, 1983–Present
density_state_org <- org %>% 
summarise(represented_share = weighted.mean(union, w=orgwgt/12, na.rm=TRUE),
          .by = c(year, statefips)) %>%
  
  #Turn statefips labels into strings
  mutate(statefips = haven::as_factor(statefips)) %>% 
  #sort by year and state
  arrange(year, statefips) %>% 
  #reshape data
  pivot_wider(id_cols = year, names_from = statefips, values_from = represented_share)

density_state_org
```
